/*
============================================================
Project:     Credit Risk Portfolio Analysis
File:        07_portfolio_concentration.sql
Phase:       2 - SQL Business Analysis
Task:        Portfolio Concentration & Risk Summary
============================================================

Business Purpose:
    Deliver a board-level portfolio concentration report
    identifying which age segments generate a disproportionate
    share of defaults relative to their share of the loan book.
    Enables the CRO to direct capital reserves, underwriting
    policy changes, and collections resources to the segments
    where default risk is most concentrated rather than
    spreading attention equally across the portfolio.

Key Techniques:
    - SUM(COUNT(*)) OVER() computes grand total within the
      same aggregation pass -- eliminates need for a subquery
      or additional CTE to obtain portfolio-wide totals
    - SUM(SUM(...)) OVER() applies same pattern to aggregated
      default counts -- outer SUM totals across all grouped
      rows, inner SUM aggregates within each group
    - UNION ALL appends a grand total row without a separate
      query -- references band_details CTE twice, once for
      band rows and once for the totals row
    - Third CTE (final_result) wraps the UNION ALL to enable
      ORDER BY -- T-SQL does not allow ORDER BY expressions
      in a UNION statement unless wrapped in an outer query
      or CTE
    - Concentration threshold of 5 percentage points chosen
      as the flag boundary -- segments within 5 points of
      their proportional share are considered Proportionate

SUM(COUNT(*)) OVER() Pattern Explained:
    After GROUP BY runs, the result set has one row per band.
    SUM(...) OVER() is a window function that then runs on
    those grouped rows. The empty OVER() means no partition --
    sum everything visible. So COUNT(*) gives the band count
    and SUM(COUNT(*)) OVER() gives the total across all bands.
    This is the SQL equivalent of the DAX ALL() pattern used
    in the Power BI measures built in Phase 3.

UNION ALL Design Decision:
    UNION ALL is used instead of UNION because there are no
    duplicate rows to eliminate -- each band row is unique and
    the Total row is a synthetic aggregate, not a duplicate.
    UNION would perform an unnecessary distinct operation
    adding overhead with no benefit.

Output:
    One row per age band plus a Total summary row showing
    BorrowerCount, Portfolio_Share_Pct, DefaultCount,
    Default_Share_Pct, and Concentration_Flag ordered
    Young through Retired with Total pinned at bottom

Key Findings:
    - Mid-Career is 13.62 points overrepresented -- generates
      51.99% of defaults while representing only 38.37% of
      the portfolio -- single most actionable finding for
      underwriting policy review
    - Senior and Retired are underrepresented by 9.61 and
      8.45 points respectively -- most stable segments,
      subsidizing risk generated by younger borrowers
    - Young sits at 4.44 points above proportionate --
      just under the 5 point flag threshold but warrants
      monitoring given their 11.73% individual default rate
    - Blended portfolio default rate is 6.68% --
      the headline number for the board presentation
============================================================
*/

WITH age_tiers AS (
    SELECT *,
        -- BETWEEN safe for integer age column
        -- Retired catches all ages 70+ via ELSE
        CASE 
            WHEN age < 30 THEN 'Young'
            WHEN age BETWEEN 30 AND 49 THEN 'Mid-Career'
            WHEN age BETWEEN 50 AND 69 THEN 'Senior'
            ELSE 'Retired'
        END AS AgeBand
    FROM cs_loans_clean
),

band_details AS (
    SELECT
        AgeBand,
        COUNT(*) AS BorrowerCount,
        -- SUM(COUNT(*)) OVER() totals all grouped COUNT(*) values
        -- across every band in a single pass -- no subquery needed
        -- Empty OVER() means no partition -- sum all bands globally
        ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS Portfolio_Share_Pct,
        SUM(CAST(SeriousDlqin2yrs AS INT)) AS DefaultCount,
        -- SUM(SUM(...)) OVER() follows the same pattern --
        -- inner SUM aggregates defaults per band via GROUP BY
        -- outer SUM(...) OVER() totals across all band rows
        -- to produce the portfolio-wide default count denominator
        ROUND(SUM(CAST(SeriousDlqin2yrs AS INT)) * 100.0 / SUM(SUM(CAST(SeriousDlqin2yrs AS INT))) OVER(), 2) AS Default_Share_Pct
    FROM age_tiers
    GROUP BY AgeBand
),

final_result AS (
    -- Band-level rows with concentration flag
    SELECT
        AgeBand,
        BorrowerCount,
        Portfolio_Share_Pct,
        DefaultCount,
        Default_Share_Pct,
        -- 5 point threshold flags meaningful concentration gaps
        -- Alias Default_Share_Pct - Portfolio_Share_Pct cannot
        -- be referenced here -- T-SQL evaluates all SELECT
        -- columns simultaneously so expression is repeated
        CASE
            WHEN (Default_Share_Pct - Portfolio_Share_Pct) > 5 THEN 'Overrepresented'
            WHEN (Default_Share_Pct - Portfolio_Share_Pct) < -5 THEN 'Underrepresented'
            ELSE 'Proportionate'
        END AS Concentration_Flag
    FROM band_details
    -- UNION ALL not UNION -- no duplicates to eliminate and
    -- UNION would add unnecessary distinct operation overhead
    UNION ALL
    -- Synthetic grand total row -- hardcoded 100.0 for both
    -- share columns since total always equals 100% by definition
    -- N/A for flag since concentration comparison is meaningless
    -- at total portfolio level
    SELECT
        'Total' AS AgeBand,
        SUM(BorrowerCount) AS BorrowerCount,
        100.0 AS Portfolio_Share_Pct,
        SUM(DefaultCount) AS DefaultCount,
        100.0 AS Default_Share_Pct,
        'N/A' AS Concentration_Flag
    FROM band_details
)

-- final_result CTE wrapper required because T-SQL does not
-- allow ORDER BY expressions directly on UNION statements
-- wrapping in a CTE resolves this without changing output
SELECT *
FROM final_result
ORDER BY
    CASE AgeBand
        WHEN 'Young' THEN 1
        WHEN 'Mid-Career' THEN 2
        WHEN 'Senior' THEN 3
        WHEN 'Retired' THEN 4
        WHEN 'Total' THEN 5  -- Total pinned to bottom
    END